[build]
  # This is the directory that Netlify will deploy (your static files)
  publish = "." 

[functions]
  # This is the directory where your serverless functions are located
  # The '.' before '/.netlify/functions' ensures it's relative to the project root.
  # We use '.netlify' because it's a hidden folder created by Netlify CLI by default.
  directory = "./.netlify/functions" 
  # You can optionally specify the Node.js version if needed
  # For example, to use Node.js version 18:
  # node_bundler = "esbuild" 
  # node_version = "18" # Uncomment and specify version if you need a specific Node.js version